Add support for GET call validation
grofers/flasgger pull request #1
Opened 2018-02-08 06:06 UTC by adi69

2018-02-13 11:38 UTC, yashmehrotra requested changes

2018-02-13 11:38 UTC, yashmehrotra commented on flasgger/utils.py
> +    CustomValidator = extend(CustomValidator, type_checker=type_checker)
Instead of doing this twice, theres a method which lets you add a mapping of redefined types

2018-02-13 11:38 UTC, yashmehrotra commented on requirements-dev.txt
> +-e git://github.com/Julian/jsonschema.git#egg=jsonschema
Why add both in requirements and requirements-dev

2018-02-13 11:38 UTC, yashmehrotra commented on flasgger/utils.py
> +    for defi in raw_definitions:
Use a better variable name than `defi`

2018-02-15 05:20 UTC, aaadityeah commented on flasgger/utils.py
> +    CustomValidator = extend(CustomValidator, type_checker=type_checker)
Yeah, I saw that , but, I had apprehensions regarding that method because it's not yet released and there are no tests written for that method. However, I do agree it's more appropriate.

2018-02-15 05:21 UTC, aaadityeah commented on requirements-dev.txt
> +-e git://github.com/Julian/jsonschema.git#egg=jsonschema
why not?

2018-02-15 05:21 UTC, aaadityeah commented on flasgger/utils.py
> +    for defi in raw_definitions:
This variable has been used in the original code

2018-02-15 06:34 UTC, yashmehrotra commented on requirements-dev.txt
> +-e git://github.com/Julian/jsonschema.git#egg=jsonschema
Because its not required

2018-02-15 07:19 UTC, yashmehrotra commented on requirements-dev.txt
> +-e git://github.com/Julian/jsonschema.git#egg=jsonschema
Because dev requirements are only for dev related packages, that is why there are 2 seperate files

2018-02-19 04:30 UTC, yashmehrotra approved these changes

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +    validate_data(
Add new line above.

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +        strict_validation = False
Add comment.

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +    data = {k.lower(): v for k, v in dict(request.headers).items()}
move to common function get_data_for_validation

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +    if not should_validate_headers:
remove this. Avoid multiple return

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +        def type_or_string_type(checker, instance):
rename

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +        if type_name == 'number':
handle bool 'true/false'

2018-02-20 07:10 UTC, niteshJindal commented on flasgger/utils.py
> +                except ValueError:
use else to return

2018-02-20 07:10 UTC, niteshJindal commented on requirements.txt
> +-e git://github.com/Julian/jsonschema.git#egg=jsonschema
use the commit id until merged to upstream.

2018-02-21 05:06 UTC, niteshJindal commented
Approved.

2018-02-21 05:13 UTC, merged